apiVersion: v1
kind: Secret
metadata:
  name: cfs-csi-api-key
  namespace: kube-system
data:
  # value need base64 encoding
  #   echo -n "<SECRET_ID>" | base64
  TENCENTCLOUD_CFS_API_SECRET_ID: "AAAAAABBBBBCCCCC"
  TENCENTCLOUD_CFS_API_SECRET_KEY: "DDDDDDEEEEEFFFFF"
